library(xgboost)
library("DALEX")
library("iBreakDown")
library(glue)
print("Library Imported")
  
  model <- xgboost::xgb.load(glue('model.model'))
  xgb.importance(model = model)
  print("Model Loaded ")
  X_train <-read.csv(glue('x_train.csv'))
  X_test <-read.csv(glue('x_test.csv'))
  y_train <-read.csv(glue('y_train.csv'))
  y_test <-read.csv(glue('y_test.csv'))
  dtrain <- xgboost::xgb.DMatrix(data = as.matrix(X_train),label = as.matrix(y_train))
  dtest <- xgboost::xgb.DMatrix(data = as.matrix(X_test),label = as.matrix(y_test))
  #print(X_train[469986,])
  #print(dtest)
  #y_proba_train <- predict(model,dtrain)
  #y_proba_test <- predict(model, dtest)
  explain_transaction<-explain(model,as.matrix(X_test),as.matrix(y_test),label="The Model")
  #print(explain_transaction)
  transaction <- X_test[5,]
  #class(as.matrix(transaction))
  #x_=as.matrix(transaction[1:11])
  #print(transaction[1:11])
  #print(x_)
  shap_rf <- shap(explain_transaction,as.matrix(transaction))
  
  plot(shap_rf)
  print(describe(shap_rf, label = "the probability that transaction can be suspicious transaction",display_values = TRUE,display_numbers = TRUE,display_shap = TRUE))
  